name : Notification Framework

on:
    workflow_dispatch:
        # inputs:
        #     owner:
        #         description: "Repository Owner"
        #         required: true
            
        #     repository:
        #         description: "Repository Name"
        #         required: true

        #     run_id:
        #         description: "Workflow Run ID"
        #         required: true
    repository_dispatch:
        types:
            - release-failure

jobs:
    notify:

        runs-on: ubuntu-latest

        steps:

            - name: Checkout Repository 
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Run Fetch Workflow Script
              env:
                OWNER: ${{ github.event.inputs.owner }}
                REPOSITORY: ${{ github.event.client_payload.repository }}
                RUN_ID: ${{ github.event.client_payload.run_id }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

              run: |
                python scripts/fetch_workflow_jobs.py

            - name: Run Download Logs Script
              env:
                OWNER: ${{ github.event.inputs.owner }}
                REPOSITORY: ${{ github.event.inputs.repository }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

              run: |
                python scripts/download_logs.py

            - name: Run Parse Logs Script
              run: |
                python scripts/parse_logs.py

            - name: Generate HTML notification
              run: |
                python scripts/generate_email.py

            - name: Send Email Notification
              env:
                SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
                SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
              run: |
                python scripts/smtp_sender.py

            - name: Upload Framework Artifact
              uses: actions/upload-artifact@v4
              with:
                name: notification-framework-artifacts
                path: artifacts/

